@startuml Firestore_Structure

class Members {
    + userId
    --
    + username
    + email
    + profilePic
    + createdAt
    + clubId
    + clubPic
}

class Clubs {
    + clubId
    --
    + clubName
    + description
    + createdAt
    + clubPic
}

class ClubMembers {
    + clubIdUserId
    --
    + clubId
    + userId
    + joinedAt
    + admin
}



class Posts {
    + postId
    --
    + userId
    + title
    + content
    + createdAt
    + imageUrl
}

class Comments {
    + commentId
    --
    + postId
    + userId
    + content
    + createdAt
}

class Likes {
    + likeId
    --
    + postId
    + userId
    + createdAt
}

Users "1" -- "*" Clubs : "belongs_to"
Clubs "1" -- "*" ClubMembers : "has"
Clubs "1" -- "*" ClubAdmins : "has"
Users "1" -- "*" Posts : "creates"
Users "1" -- "*" Comments : "writes"
Users "1" -- "*" Likes : "likes"

@enduml
